apiVersion: v1
kind: Service
metadata:
  name: reactive-web-pubsub
  namespace: vivek-cluster-namespace
spec:
  selector:
    app: reactive-web-pubsub
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
